### ISSUE TITLE
Dark theme?

### ISSUE THREAD

**Issue by thamaragerigr** [OSWeekends/agenda#100]
¿Qué opinas de agregarle a la agenda un modo noche? 👥👀

**Comment by baumannzone** [comment]
100% OK

**Comment by thamaragerigr** [comment]
Esta es mi propuesta (puede que cambie algunas cosas):

![Desktop](https://user-images.githubusercontent.com/52920777/97732363-b9f38580-1ad6-11eb-880c-e870223bcb92.png)

Si no te convence algo o lo que sea dime plis 🙏

**Comment by baumannzone** [comment]
Me encanta, ¡vamos a ponernos a ello!

**Comment by thamaragerigr** [comment]
He sacado unas paletas de colores en figma: 
![image](https://user-images.githubusercontent.com/52920777/97792593-75541100-1be0-11eb-83c4-cca6ac2a9e3f.png)

Y vuelto a cambiar algunos tonos 🥺:
![Desktop](https://user-images.githubusercontent.com/52920777/97792600-8d2b9500-1be0-11eb-8c45-73926bab194a.png)

**Comment by peoplenarthax** [comment]
Is anybody working on the implementation of this?

I created a branch and I can try to use the palette you proposed :D

**Comment by baumannzone** [comment]
- la paleta es lo que diga @thamaragerigr
- crear themes 👏👏👏
- por el momento no hay nadie trabajado en esto

**Comment by thamaragerigr** [comment]
¡Hola @peoplenarthax!  🌈¡Supergracias por la ayuda! (●'◡'●) 🌈[Aquí ](https://www.figma.com/file/FY1tWiZcFsKq4jpAeYBB43/OSW-Agenda?node-id=0%3A1) puedes ver lo que teniamos pensado en figma.

**Comment by peoplenarthax** [comment]
Hola hola @thamaragerigr !

Habia pensado hacerlo de la manera que menos duele para empezar:
- Crear CSS Variables y sustituir todos los usos de colores por estas variables.
- Usar Color Semantico en lugar de colores, e.g. en lugar de `blue` `dark-blue`, usaria `main`, `background`, `background-light` 
- Usando un switch, sobreescribir las CSS variables por los valores de la otra paleta
- Persistir usando local storage la preferencia del usuario

Por cierto, alguna idea de donde/como hacer el botton para cambiar entre el dark theme y el light theme? Si no puedo improvisar :D

**Comment by thamaragerigr** [comment]
Ahora que lo dices se me paso pensar en el switch XDD. Rapidamente se me ocurre algo así, si les parece bien claro (✿◕‿◕✿)

![image](https://user-images.githubusercontent.com/52920777/101783181-39bf3780-3afa-11eb-9653-bbe31273e726.png)

![image](https://user-images.githubusercontent.com/52920777/101783115-26ac6780-3afa-11eb-8db2-1a6f7660eff9.png)

**Comment by peoplenarthax** [comment]
> Ahora que lo dices se me paso pensar en el switch XDD. Rapidamente se me ocurre algo así, si les parece bien claro (✿◕‿◕✿)
> 
> ![image](https://user-images.githubusercontent.com/52920777/101783181-39bf3780-3afa-11eb-9653-bbe31273e726.png)
> 
> ![image](https://user-images.githubusercontent.com/52920777/101783115-26ac6780-3afa-11eb-8db2-1a6f7660eff9.png)

Simple y resalta lo suficiente (ya he visto que lo has actualizado en figma.
A lo mejor en el dark theme es algo mas... sutil, pero lo implemento y se puede iterar de nuevo sobre los colores :D

**Comment by peoplenarthax** [comment]
Me acabo de dar cuenta de que no he implementado la transicion para los colores. Podemos hacer esto en otra PR

**Comment by baumannzone** [comment]
Acabo de mergearlo a `dev`, cuando lo revise lo pasamos a master y te damos full reconocimientos en el siguiente evento de #OSWonline, de momento mantenemos el secreto 😱

**Comment by baumannzone** [comment]
> Me acabo de dar cuenta de que no he implementado la transicion para los colores. Podemos hacer esto en otra PR

En otra PR es ok

**Comment by thamaragerigr** [comment]
OMG ¡¡¡¡Lo acabo de ver me superencanta!!!! (❤ ω ❤) ¡¡Muchísimas gracias!!
