### ISSUE TITLE
Align "online" tag with the text

### ISSUE THREAD

**Issue by baumannzone** [OSWeekends/agenda#104]
The `online` text is above the text baseline. 
![image](https://user-images.githubusercontent.com/5422102/97789554-b4269e80-1bc1-11eb-889b-acac6487f725.png)

**Comment by nelodev** [comment]
Me la quedo

**Comment by baumannzone** [comment]
Component: `BaseHeader.vue`

**Comment by nelodev** [comment]
Esta se puede cerrar ya no? @baumannzone

**Comment by baumannzone** [comment]
Si. La próxima vez, en el mensaje del commit pones esto: `close #XX` y cuando se haga el pr, la issue se cierra automáticamente 😊👌
