### ISSUE TITLE
"Dia del evento" tiene que cambiar cuando se cambie de zona horaria

### ISSUE THREAD

**Issue by baumannzone** [OSWeekends/agenda#108]
Cuando cambias la zona horaria del evento, actualmente, no se está teniendo en cuenta el día.

Si cambiamos a `-12` horas y el evento empieza a las 10 de la mañana, el dia del evento debería cambiar para que sea un día menos, además de las horas (que ya está funcionando)

¿@jorge-bajana te encargas de esto también?

**Comment by baumannzone** [comment]
Relaccionado con #95 y #105

**Comment by jorge-bajana** [comment]
Vale! Voy a ver que pasa con esto
