### ISSUE TITLE
Custom Agenda Colors

### ISSUE THREAD

**Issue by baumannzone** [OSWeekends/agenda#110]
**Is your feature request related to a problem? Please describe.**
It would be nice if we could customize the agenda by providing a color-palette file

**Describe the solution you'd like**
Possibility to create a palette-color / theme file with the colors you want

**Describe alternatives you've considered**
Something like this:
```
main-color: black
secondary-color: yellow
...
```

**Comment by thamaragerigr** [comment]
What do you think of this implementation for the color handling throughout the app? 

A styles folder with three files: 
* 'colors.scss' with all the variables.
* 'lightTheme.scss' which would be a class for the light mode.
* 'darkTheme.scss' which would be a class for the dark mode.

(I made a diagram in case I'm not explaining myself right 👇👇👇)

![image](https://user-images.githubusercontent.com/52920777/98461759-2e9d8280-21af-11eb-9a22-5d6841bb2856.png)

**Comment by peoplenarthax** [comment]
Esta PR (https://github.com/OSWeekends/agenda/pull/117) usa el principio de los colores semanticos, asique potencialmente podriamos crear diferentes temas.

Podemos revisitar el nombre de las variables CSS

**Comment by baumannzone** [comment]
💃 Ya lo hemos mergeado, muchas gracias @peoplenarthax, eres un 🧞‍♂️!

**Comment by thamaragerigr** [comment]
Que Dios te bendiga @peoplenarthax 🙏😭
