### ISSUE TITLE
Remove `bootstrap-vue`

### ISSUE THREAD

**Issue by peoplenarthax** [OSWeekends/agenda#128]
`bootstrap-vue` dificulta la personalización de la web (muchos estilos necesitan `!important` para sobre escribir los estilos impuestos por bootstrap.

También hace la web [algo más pesada ](https://bundlephobia.com/result?p=bootstrap-vue@2.21.1) (sin contar el tree shake)

Como la web no usa componentes muy complejos de bootstrap tal vez podriamos sustituir todo el scaffolding con css-grid / flexbox.

¿Opiniones?

**Comment by baumannzone** [comment]
Usamos tailwind css

**Comment by peoplenarthax** [comment]
Todo es probar! No lo he usado nunca pero... no veo que pueda hacer daño. Puedo empezar un branch estos días y ver que cosas cambian con respecto a bootstrap. @thamaragerigr, revisarías los cambios en diseño cuando la rama este más lista?
