### ISSUE TITLE
Nueva charla - 16 de noviembre

### ISSUE THREAD

**Issue by ValKiriann** [OSWeekends/agenda#20]
**Titulo:** Solution+Software Engineering: Trucos para usar nuestro arte en soluciones viables
**Descripción:** La teoría nos dice que desarrollo de software es una ingeniería. La práctica nos revela que hay mucho de nuestra industria que es muy dificil poner en papel. Como por ejemplo: ¿Como sabes que la solución que estamos implementando es la correcta? Esta charla se enfoca en la labor creativa antes de la solución y como construir un solución efectiva y flexible a los problemas que queremos arreglar para nosotros, otros o el mundo. 
**Nivel Técnico:** Principiante
**Autor:** Andrés Vidal, Arquitecto de Software en Bnext
**Timing**: 45
**Redes**: https://www.linkedin.com/in/andrespvidal/

**Comment by baumannzone** [comment]
puedes preguntarle por 3 "tags", como por ejemplo: 'software', 'IoT' y 'seguridad'
