### ISSUE TITLE
Agregar link con el mapa

### ISSUE THREAD

**Issue by baumannzone** [OSWeekends/agenda#21]
Si el evento es físico: mostrar mapa
Si el evento es virtual: mostrar url

**Comment by thamaragerigr** [comment]
¿Te refieres a un iframe de google maps? 🤠

**Comment by baumannzone** [comment]
Con un link nos vale, no hace falta un iframe incrustado 🤝

**Comment by thamaragerigr** [comment]
A la ubicación del Google Campus ¿no?

**Comment by baumannzone** [comment]
Si, pero ahora mismo no tiene mucho sentido..

Habría que poner un dato que controle si el evento es físico o virtual. SI es fisico, te muestra el link del mapa, si es virtual te saca enlace del twitch.

**Comment by thamaragerigr** [comment]
oki guay! 💪🤠
