### ISSUE TITLE
Nuevo diseño

### ISSUE THREAD

**Issue by baumannzone** [OSWeekends/agenda#54]
Subir diseño para la nueva versión de la agenda

**Comment by baumannzone** [comment]
@thamaragerigr todo tuyo, genera las imágenes, y las subes a una carpeta, llamala `/diseños` o algo asi en el repo

**Comment by thamaragerigr** [comment]
Pero ¿primero quieres que corriga las cositas que me habías dicho antes sobre el diseño?

**Comment by baumannzone** [comment]
Súbelo así 👌

**Comment by thamaragerigr** [comment]
Listo! #57
