### ISSUE TITLE
Imagen avatar del autor / grupo de meetup

### ISSUE THREAD

**Issue by baumannzone** [OSWeekends/agenda#6]

**Comment by thamaragerigr** [comment]
¡Hola! ¿A qué te refieres con esto exactamente?

**Comment by baumannzone** [comment]
Una imagen de avatar como esta que tenemos aquí en github, por ejemplo

**Comment by thamaragerigr** [comment]
¿Quieres que lo agregue al diseño?

**Comment by thamaragerigr** [comment]
Ya lo tendrías aquí 🤠 #60
