### ISSUE TITLE
Icono de Persona en Autores

### ISSUE THREAD

**Issue by baumannzone** [OSWeekends/agenda#7]

**Comment by thamaragerigr** [comment]
¿Te refieres a aquí?:
![image](https://user-images.githubusercontent.com/52920777/94582864-0c921580-027d-11eb-9f31-ba6a7a7cb73b.png) 
¿O aquí? 
![image](https://user-images.githubusercontent.com/52920777/94583018-3fd4a480-027d-11eb-9cb7-caeb11384f22.png)

**Comment by baumannzone** [comment]
Pensaba que era buena idea en la segunda opción, al lado del autor, pero si tienes alguna propuesta mejor, lo vemos :D
