### ISSUE TITLE
API twitch

### ISSUE THREAD

**Issue by baumannzone** [OSWeekends/agenda#90]
Create some cool effect if the twitch user `osweekends` is live and add some link to the streaming

**Comment by nelodev** [comment]
¿Me puedo quedar con esta? @baumannzone Le estoy dando una vuelta y ya tengo algo montado

**Comment by baumannzone** [comment]
Perfecto, dale ahí. A ver que tienes en mente! 🥳

**Comment by nelodev** [comment]
¿Puedes echarle un vistazo al DM de Twitter? @baumannzone
